export const AVA_ACTION_IDS = {
  START_TODAYS_WORKOUT: 'START_TODAYS_WORKOUT',
  OPEN_WORKOUT: 'OPEN_WORKOUT',
  OPEN_READINESS: 'OPEN_READINESS',
  OPEN_RECOVERY: 'OPEN_RECOVERY',
  OPEN_NUTRITION: 'OPEN_NUTRITION',
  START_RECOVERY_FLOW: 'START_RECOVERY_FLOW',
  OPEN_COACH_HUB: 'OPEN_COACH_HUB',
  OPEN_CLIENT_PROFILE: 'OPEN_CLIENT_PROFILE',
  OPEN_CLIENT_INTELLIGENCE: 'OPEN_CLIENT_INTELLIGENCE',
  OPEN_WEEKLY_REVIEWS: 'OPEN_WEEKLY_REVIEWS',
  SHOW_CLIENTS_NEEDING_ATTENTION: 'SHOW_CLIENTS_NEEDING_ATTENTION',
  SHOW_CLIENTS_MISSING_CHECKIN: 'SHOW_CLIENTS_MISSING_CHECKIN',
  SHOW_RECOVERY_CONCERNS: 'SHOW_RECOVERY_CONCERNS',
  SHOW_TRAINING_CONCERNS: 'SHOW_TRAINING_CONCERNS',
  SHOW_NUTRITION_CONCERNS: 'SHOW_NUTRITION_CONCERNS',
  SHOW_CLIENT_FOLLOWUPS: 'SHOW_CLIENT_FOLLOWUPS',
  CLIENT_SUMMARY: 'CLIENT_SUMMARY',
  APPLY_PLAN_PROPOSAL: 'APPLY_PLAN_PROPOSAL',
  CANCEL_PLAN_PROPOSAL: 'CANCEL_PLAN_PROPOSAL',
}

export const AVA_ACTION_DOMAINS = {
  WORKOUT: 'workout',
  READINESS: 'readiness',
  RECOVERY: 'recovery',
  NUTRITION: 'nutrition',
  COACH: 'coach',
}

export const AVA_COACH_ACTION_IDS = [
  AVA_ACTION_IDS.OPEN_COACH_HUB,
  AVA_ACTION_IDS.OPEN_CLIENT_PROFILE,
  AVA_ACTION_IDS.OPEN_CLIENT_INTELLIGENCE,
  AVA_ACTION_IDS.OPEN_WEEKLY_REVIEWS,
  AVA_ACTION_IDS.SHOW_CLIENTS_NEEDING_ATTENTION,
  AVA_ACTION_IDS.SHOW_CLIENTS_MISSING_CHECKIN,
  AVA_ACTION_IDS.SHOW_RECOVERY_CONCERNS,
  AVA_ACTION_IDS.SHOW_TRAINING_CONCERNS,
  AVA_ACTION_IDS.SHOW_NUTRITION_CONCERNS,
  AVA_ACTION_IDS.SHOW_CLIENT_FOLLOWUPS,
  AVA_ACTION_IDS.CLIENT_SUMMARY,
]

export const isCoachAvaAction = (actionId = '') =>
  AVA_COACH_ACTION_IDS.includes(String(actionId ?? '').trim())

export const isCoachQueryAction = (actionId = '') =>
  [
    AVA_ACTION_IDS.SHOW_CLIENTS_NEEDING_ATTENTION,
    AVA_ACTION_IDS.SHOW_CLIENTS_MISSING_CHECKIN,
    AVA_ACTION_IDS.SHOW_RECOVERY_CONCERNS,
    AVA_ACTION_IDS.SHOW_TRAINING_CONCERNS,
    AVA_ACTION_IDS.SHOW_NUTRITION_CONCERNS,
    AVA_ACTION_IDS.SHOW_CLIENT_FOLLOWUPS,
    AVA_ACTION_IDS.CLIENT_SUMMARY,
  ].includes(String(actionId ?? '').trim())

export const AVA_ACTION_CONFIRMATION = {
  NONE: 'none',
  REQUIRED: 'required',
}

export const AVA_ACTION_SOURCE = {
  DETERMINISTIC: 'deterministic',
  MODEL: 'model',
  UI: 'ui',
  REFERENT: 'referent',
}

export const AVA_ACTION_STAGE = {
  RESOLVED: 'resolved',
  CONFIRMATION: 'confirmation',
  EXECUTING: 'executing',
  VERIFIED: 'verified',
  FAILED: 'failed',
}

export const AVA_ACTION_OUTCOME_KIND = {
  ACTION_READY: 'action_ready',
  ACTION_CONFIRMATION: 'action_confirmation',
  ACTION_SUCCESS: 'action_success',
  ACTION_FAILURE: 'action_failure',
  ACTION_CANCELLED: 'action_cancelled',
}

/** Maps legacy model / conversation kebab IDs to registry IDs. */
export const LEGACY_ACTION_ID_MAP = {
  'start-workout': AVA_ACTION_IDS.START_TODAYS_WORKOUT,
  'continue-workout': AVA_ACTION_IDS.START_TODAYS_WORKOUT,
  START_WORKOUT: AVA_ACTION_IDS.START_TODAYS_WORKOUT,
  CONTINUE_WORKOUT: AVA_ACTION_IDS.START_TODAYS_WORKOUT,
  'open-readiness': AVA_ACTION_IDS.OPEN_READINESS,
  OPEN_READINESS: AVA_ACTION_IDS.OPEN_READINESS,
  'start-recovery': AVA_ACTION_IDS.START_RECOVERY_FLOW,
  START_RECOVERY: AVA_ACTION_IDS.START_RECOVERY_FLOW,
  OPEN_MOBILITY: AVA_ACTION_IDS.START_RECOVERY_FLOW,
  'open-nutrition': AVA_ACTION_IDS.OPEN_NUTRITION,
  OPEN_NUTRITION: AVA_ACTION_IDS.OPEN_NUTRITION,
}

export const normalizeAvaActionId = (value = '') => {
  const key = String(value ?? '').trim()
  if (!key) return null
  if (Object.values(AVA_ACTION_IDS).includes(key)) return key
  return LEGACY_ACTION_ID_MAP[key] ?? null
}
