export const COACH_ATTENTION_CATEGORY = {
  CHECK_IN_CONCERN: 'CHECK_IN_CONCERN',
  PAIN_OR_DISCOMFORT: 'PAIN_OR_DISCOMFORT',
  NO_NEXT_APPOINTMENT: 'NO_NEXT_APPOINTMENT',
  LOW_SESSION_BALANCE: 'LOW_SESSION_BALANCE',
  MISSED_APPOINTMENT: 'MISSED_APPOINTMENT',
  MISSED_TRAINING: 'MISSED_TRAINING',
  PROGRAM_CHANGE_REQUEST: 'PROGRAM_CHANGE_REQUEST',
  RECOVERY_CONCERN: 'RECOVERY_CONCERN',
  ATHLETE_QUESTION: 'ATHLETE_QUESTION',
}

export const ATTENTION_CATEGORY_PRIORITY = {
  [COACH_ATTENTION_CATEGORY.PAIN_OR_DISCOMFORT]: 96,
  [COACH_ATTENTION_CATEGORY.MISSED_APPOINTMENT]: 94,
  [COACH_ATTENTION_CATEGORY.RECOVERY_CONCERN]: 92,
  [COACH_ATTENTION_CATEGORY.ATHLETE_QUESTION]: 88,
  [COACH_ATTENTION_CATEGORY.PROGRAM_CHANGE_REQUEST]: 86,
  [COACH_ATTENTION_CATEGORY.CHECK_IN_CONCERN]: 74,
  [COACH_ATTENTION_CATEGORY.MISSED_TRAINING]: 70,
  [COACH_ATTENTION_CATEGORY.LOW_SESSION_BALANCE]: 56,
  [COACH_ATTENTION_CATEGORY.NO_NEXT_APPOINTMENT]: 42,
}

export const ATTENTION_CATEGORY_LABEL = {
  [COACH_ATTENTION_CATEGORY.CHECK_IN_CONCERN]: 'Check-in concern',
  [COACH_ATTENTION_CATEGORY.PAIN_OR_DISCOMFORT]: 'Pain or discomfort',
  [COACH_ATTENTION_CATEGORY.NO_NEXT_APPOINTMENT]: 'No next session scheduled',
  [COACH_ATTENTION_CATEGORY.LOW_SESSION_BALANCE]: 'Low session balance',
  [COACH_ATTENTION_CATEGORY.MISSED_APPOINTMENT]: 'Missed appointment',
  [COACH_ATTENTION_CATEGORY.MISSED_TRAINING]: 'Missed training',
  [COACH_ATTENTION_CATEGORY.PROGRAM_CHANGE_REQUEST]: 'Program change request',
  [COACH_ATTENTION_CATEGORY.RECOVERY_CONCERN]: 'Recovery concern',
  [COACH_ATTENTION_CATEGORY.ATHLETE_QUESTION]: 'Athlete question',
}

export const ATTENTION_CATEGORY_ACTION = {
  [COACH_ATTENTION_CATEGORY.NO_NEXT_APPOINTMENT]: 'Schedule',
  [COACH_ATTENTION_CATEGORY.LOW_SESSION_BALANCE]: 'Review passes',
  [COACH_ATTENTION_CATEGORY.MISSED_APPOINTMENT]: 'Open client',
  [COACH_ATTENTION_CATEGORY.CHECK_IN_CONCERN]: 'Review check-in',
  [COACH_ATTENTION_CATEGORY.PAIN_OR_DISCOMFORT]: 'Review follow-up',
  [COACH_ATTENTION_CATEGORY.PROGRAM_CHANGE_REQUEST]: 'Review follow-up',
  [COACH_ATTENTION_CATEGORY.RECOVERY_CONCERN]: 'Review client',
  [COACH_ATTENTION_CATEGORY.MISSED_TRAINING]: 'Review client',
  [COACH_ATTENTION_CATEGORY.ATHLETE_QUESTION]: 'Review follow-up',
}
