import { CalendarRange, Copy, Plus, Send, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { coachBackend } from '../lib/coachBackend'
import SectionHeader from './ui/SectionHeader'
import EmptyState from './ui/EmptyState'

const emptyProgram = () => ({ name: '', description: '', durationWeeks: 4, days: [{ weekday: 1, kind: 'workout', title: '', templateId: '' }] })

export default function CoachPrograms({ clients, templates, program, onRefresh }) {
  const [programs,setPrograms]=useState([]), [editing,setEditing]=useState(null), [assigning,setAssigning]=useState(null), [notice,setNotice]=useState('')
  const [assignment,setAssignment]=useState({ athleteId:'', startDate:new Date().toISOString().slice(0,10) })
  const load=async()=>{try{setPrograms(await coachBackend.listPrograms())}catch(error){setNotice(error.message)}}
  useEffect(()=>{load()},[])
  const library=[...templates.map(t=>({id:`template:${t.id}`,name:t.name,workout:t.workout_payload})),...Object.entries(program?.workouts??{}).map(([name,exercises])=>({id:`program:${name}`,name,workout:{name,exercises}}))]
  const save=async()=>{const hydrated={...editing,days:editing.days.map(day=>day.kind==='workout'?{...day,workoutPayload:library.find(item=>item.id===day.templateId)?.workout??day.workoutPayload}:day)};await coachBackend.saveProgram(hydrated);setEditing(null);setNotice('Program saved.');await load();await onRefresh?.()}
  const publish=async()=>{await coachBackend.assignProgram({ programId:assigning.id, athleteId:assignment.athleteId, startDate:assignment.startDate });setAssigning(null);setNotice('Program published to client calendar.');await onRefresh?.()}
  return <section className="coach-programs-screen"><SectionHeader eyebrow="MULTI-WEEK PROGRAMMING" title="Programs" description="Build reusable weekly structures and publish them to any client calendar." action={<button className="gold-button machined" onClick={()=>setEditing(emptyProgram())}><Plus size={16}/>New Program</button>}/>{notice&&<p className="coach-hub-notice">{notice}</p>}
    {programs.length?<div className="coach-program-grid">{programs.map(item=><article key={item.id}><div><strong>{item.name}</strong><span>{item.duration_weeks} weeks · {item.program_payload?.days?.length??0} scheduled days</span><p>{item.description}</p></div><div><button onClick={()=>setEditing({id:item.id,name:item.name,description:item.description,durationWeeks:item.duration_weeks,days:item.program_payload?.days??[]})}><Copy size={15}/>Edit</button><button onClick={()=>setAssigning(item)}><Send size={15}/>Assign</button><button onClick={async()=>{if(confirm(`Delete ${item.name}?`)){await coachBackend.deleteProgram(item.id);await load()}}}><Trash2 size={15}/></button></div></article>)}</div>:<EmptyState icon={CalendarRange} title="No programs yet" description="Build a repeatable 4, 8, 12, or 16-week program."/>}
    {editing&&<div className="coach-designer-backdrop"><section className="coach-program-editor"><header><div><span className="eyebrow">PROGRAM BUILDER</span><h2>{editing.id?'Edit program':'New program'}</h2></div><button onClick={()=>setEditing(null)}><Trash2 size={17}/></button></header><label><span>Name</span><input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label><span>Description</span><textarea rows={3} value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label><span>Duration</span><select value={editing.durationWeeks} onChange={e=>setEditing({...editing,durationWeeks:Number(e.target.value)})}>{[4,8,12,16].map(value=><option key={value} value={value}>{value} weeks</option>)}</select></label><div className="coach-program-days">{editing.days.map((day,index)=><article key={index}><select value={day.weekday} onChange={e=>setEditing({...editing,days:editing.days.map((item,i)=>i===index?{...item,weekday:Number(e.target.value)}:item)})}>{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((name,i)=><option key={name} value={i}>{name}</option>)}</select><select value={day.kind} onChange={e=>setEditing({...editing,days:editing.days.map((item,i)=>i===index?{...item,kind:e.target.value}:item)})}><option value="workout">Workout</option><option value="rest">Rest</option><option value="deload">Deload</option></select>{day.kind==='workout'?<select value={day.templateId} onChange={e=>setEditing({...editing,days:editing.days.map((item,i)=>i===index?{...item,templateId:e.target.value,title:library.find(x=>x.id===e.target.value)?.name??''}:item)})}><option value="">Choose workout</option>{library.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>:<input value={day.title} onChange={e=>setEditing({...editing,days:editing.days.map((item,i)=>i===index?{...item,title:e.target.value}:item)})} placeholder={day.kind==='rest'?'Rest Day':'Deload Day'}/>}<button onClick={()=>setEditing({...editing,days:editing.days.filter((_,i)=>i!==index)})}><Trash2 size={15}/></button></article>)}</div><button className="coach-secondary-button" onClick={()=>setEditing({...editing,days:[...editing.days,{weekday:1,kind:'workout',title:'',templateId:''}]})}><Plus size={15}/>Add Day</button><button className="gold-button machined" onClick={save}>Save Program</button></section></div>}
    {assigning&&<div className="coach-designer-backdrop"><section className="coach-program-editor"><header><div><span className="eyebrow">ASSIGN PROGRAM</span><h2>{assigning.name}</h2></div><button onClick={()=>setAssigning(null)}><Trash2 size={17}/></button></header><label><span>Client</span><select value={assignment.athleteId} onChange={e=>setAssignment({...assignment,athleteId:e.target.value})}><option value="">Select client</option>{clients.map(client=><option key={client.id} value={client.athlete_id}>{client.athlete_email}</option>)}</select></label><label><span>Start date</span><input type="date" value={assignment.startDate} onChange={e=>setAssignment({...assignment,startDate:e.target.value})}/></label><button className="gold-button machined" disabled={!assignment.athleteId} onClick={publish}><Send size={16}/>Publish Program</button></section></div>}
  </section>
}
